---
title: "Replication of Study 3 in “Anticipating divine protection? Reminders of god can increase nonmoral risk taking” by Kupor, D. M., Laurin, K., & Levav, J. (Psychological Science 26.4 (2015): 374-384)"
author: "Katherine Flaschen (kflasche@stanford.edu)"
output: html_document
---

## Introduction
In this study, Kupor, Laurin, and Levav (2015) demonstrated that priming God increased people’s willingness to take nonmoral risks.  Further, they showed that this effect was mediated by perceived risk.  Specifically, reminders of God (as opposed to a control condition) led individuals to perceive nonmoral risk as less dangerous, which in turn led to an increased willingness to take such risk.  The authors suggested that reminders of God led to less perceived risk because such reminders evoked a feeling of safety from potential harm, although this was tested more directly in a subsequent study.

## Methods
### Power Analysis
The original study reports that:

a) Participants in the God condition reported a higher willingness to take risks, *b* = .61, *t*(99) = 2.29, *p* = .024, than did participants in the control condition.
b) Participants in the God condition also perceived less danger associated with these risks, *b* = -0.44, *t*(99) = -2.97, *p* = .004, than did participants in the control condition.
c) When the effects of God condition and perceived danger were both included in the model, the indirect effect (i.e., through the mediator) was significant (95% confidence interval, or CI = [0.12, 0.64]), whereas the direct effect (i.e., the effect of condition independent of the mediator) was not significant, *b* = 0.28, *t*(98) = 1.12, *p* = .267.

Because I didn't have enough information to calculate the effect size of the indirect effect, I calculated the effect size for the IV's effect on the DV, as well as the effect size for the IV's effect on the mediator:

a) *b* = .61, *t*(99) = 2.29, *p* = .02 (Cohen's d = .46)
b) *b* = -0.44, *t*(99) = -2.97, *p* = .004 (Cohen's d = .60)

Then, I took the smaller of these two effect sizes, Cohen's d = .46, for my power analysis:
```{r Power Analysis}
power.t.test(delta=0.46, sd=1, power=.95, sig.level=0.05)
power.t.test(delta=0.46, sd=1, power=.90, sig.level=0.05)
power.t.test(delta=0.46, sd=1, power=.80, sig.level=0.05)
```

### Planned Sample
The original study uses a sample size of 101 participants, which, from a post hoc analysis, results in 63% power.  Therefore, I have chosen to run my replication with 200 participants, which is the number of participants needed to achieve 90% power.

Like the original authors, I will have no specific criteria for participant demographics.  The original study cited a mean age of 31.4 years, 64.4% male and 35.6% female.  

The authors did not allow participants who had taken one of their previous experiments on God and risk taking to participate in their study.  I will not need to adhere to this preselection rule, but I will exclude any participant who reports having seen any of the information used in my replication in a previous study (see d under "Differences from Original Study" section).  Further, from speaking with the authors, they believe that their MTurk qualifications restricted workers to a US location, non-masters, and an 85% approval percentage.  I will adhere to these qualifications. 

### Materials
I was fortunate enough to have the original study shared with me by the authors.  Therefore, I will adhere to the original study's wording exactly, unless otherwise mentioned in the "Differences from Original Study" section.  The bulk of the content is listed below:

<b>Priming Conditions:</b> <br>
<u>God Prime Condition: </u> <br>
*"God is often thought of as a supreme being. Theologians have described God as having many attributes, including omniscience (infinite knowledge), omnipotence (unlimited power), omnipresence (present everywhere), and omnibenevolence (perfect goodness). God has also been conceived as being incorporeal (immaterial), a personal being, and the 'greatest conceivable existent.'"* (adapted from Wikipedia: http://en.wikipedia.org/wiki/God) 

<u>Control Condition: </u> <br> 
*"In 2006, the International Astronomers’ Union passed a resolution outlining three conditions for an object to be called a planet. First, the object must orbit the sun; second, the object must be a sphere; and third, it must have cleared the neighborhood around its orbit. Pluto does not meet the third condition, and is thus not a planet."* (adapted from Wikipedia: http://en.wikipedia.org/wiki/Pluto)

<b>Nonmoral Risk Scenarios:</b> <br>
<u>Motorcycle Scenario: </u> <br>
*"Imagine that you have a motorcycle that you love to ride. It is a nice day outside, and you are planning to ride your motorcycle to a nearby park to have a picnic. Since it's such a beautiful day out, you are thinking about riding your motorcycle without a helmet so that you can feel the wind in your face and have a better ride to the park. However, if you decide to take the risk and not wear a helmet, there is a greater chance of being injured if you get into an accident."*

<u>Wilderness Camping Scenario: </u> <br>
*"Imagine that you are planning a trip to Guatemala, and you are looking online to see what kinds of activities you could do during your trip. You enjoy wilderness camping, and you see a website that describes a Guatemalan wilderness area that people can camp in. The wilderness area looks magnificent. You know that you would have an amazing time camping in this wilderness area. However, the website notes that if you decide to take the risk and go camping in this area, there are dangers that you could face (such as potentially dangerous wild animals and weather)."*

<u>Backcountry Skiing Scenario: </u> <br>
*"Imagine that you like to ski, and you are deciding whether or not to spend the day backcountry skiing. Backcountry skiing is skiing on an unmarked slope that is not maintained, monitored, or patrolled by anyone. You are thinking that backcountry skiing would be a great experience. However, if you decide to take the risk and go backcountry skiing, there is a chance that you could get injured by an avalanche, rock fall, or weather."*

### Procedure
I will follow the original study's procedure exactly, unless otherwise noted in the "Differences from Original Study" section.  Is it worth noting that the "ostensibly unrelated survey" (see reference below) will be introduced in the exact same manner in my replication as in the original study.  Namely, the study description and instructions page of the study will note that the session consists of two separate surveys.  Additionally, the second survey will be introduced with the brief transition text, "You will now complete questions for a separate survey. Please click the next button to continue."  The original study's procedure is outlined below: 
“One hundred one participants (mean age = 31.4 years; 64.4% male, 35.6% female) completed this study. We obtained these participants by posting 100 HITs on MTurk. We randomly assigned participants to either the God condition or the control condition from Study 1d. In an ostensibly unrelated survey, participants read three scenarios that each described a risky decision (motorcycling without a helmet, wilderness camping, and backcountry skiing). After reading each scenario, participants completed three items assessing their perceptions of danger: “If you did [e.g., go wilderness camping], what is the likelihood that you will get injured?” (1 = extremely unlikely, 7 = extremely likely), “If you did get injured while [e.g., wilderness camping], how serious do you think the injury would be?” (1 = not serious at all, 7 = extremely serious), and “If you did get injured while [e.g., wilderness camping], how well would you be able to cope with the injury?” (1 = not well at all, 7 = extremely well; reverse coded). We created an index of the nine subjective-danger-perception items (with higher scores representing more perceived danger; α  = .71). Finally, participants reported how willing they would be to take each risk (1 = not likely at all, 7 = extremely likely), which yielded an index of risk taking (α  = .60).”

### Analysis Plan
The original authors did not exclude any participants from the data analysis.  I will run the following analyses both on all participants (see d and e under "Differences from Original Study" section for exceptions) and only on participants who spend at least 5 seconds reading the priming (God vs. control) excerpt.  Although the original authors did not do this, I think this is consistent with research best practices, as I would not expect the priming condition to have an effect on any participant who did not read the excerpt.

First, the original authors found that a linear mixed model that included scenario (three levels, dummy coded), condition, and the terms representing their interaction did not differ from the results of the model without the interaction, *χ2*(2, *N* = 101) = 1.24, *p* = .539, which indicates that scenario did not moderate the effect of condition on willingness to take risks.  Therefore, the authors collapsed the perceived risk items and risk taking items across the three risky scenarios for the following analyses.  Also, as an additional check, the authors performed the following mediation analysis for each scenario individually, which I will do as well.  If I do indeed find that scenario moderated the effect of condition on willingness to take risks, these additional analyses will allow me to pinpoint which scenarios fit with the authors' mediation hypothesis, and which scenarios did not.

Next, like the original authors, I will run a mediation analysis: "Our primary analysis tested the indirect effect (Hayes, 2013) using willingness to take risks as the dependent variable, priming condition (God = 1, control = 0) as the independent variable, and perceived risk as the mediating variable—this test confirmed our predictions. Specifically, participants in the God condition reported a higher willingness to take risks, *b* = 0.61, *t*(99) = 2.29, *p* = .024, and also perceived less danger associated with these risks, *b* = −0.44, *t*(99) = −2.97, *p* = .004, than did participants in the control condition. When the effects of God condition and perceived danger were both included in the model, the indirect effect (i.e., through the mediator) was significant (95% confidence interval, or CI = [0.12, 0.64]), whereas the direct effect (i.e., the effect of condition independent of the mediator) was not significant, *b* = 0.28, *t*(98) = 1.12, *p* = .267."

Additionally, as the authors included in their Supplemental Material, I will run the above mediation analysis three additional times, treating each item in the perceived risk index individually as the mediating variable. The authors found that, "A mediation comparison analysis (Hayes, 2013) revealed no significant differences between the indirect effects. Specifically, the analysis revealed no difference between the coping ability and the seriousness of negative consequences indirect effects (CI: -.5741 to .0569), no difference between the likelihood of negative consequences and coping ability indirect effects (CI: -.5720 to .0052), and no difference between the likelihood of negative consequences and seriousness of negative consequences indirect effects (CI: -.2844 to .1239)."

Finally, as the authors depicted in their Supplemental Material, I will use participants' response to the question, "Do you believe in God?" ("yes" or "no"), asked at the end of the study, to determine if belief in God moderates the effect of condition on willingness to take risks.  The authors found that belief in God did not moderate the effect of condition on risk taking (believers: *t*(66) = 1.54, *p* = .128, *d* = .37; non-believers: *t*(30) = 1.69, *p* = .102, *d* = .62).

### Differences from Original Study
Given that the original study was run on MTurk and that I have all the exact materials from the original study, I anticipate few differences from the original study.  The differences I do anticipate are listed below:

a) Whereas the original study had a sample size of 101 participants (with 63% power), I will use 200 participants in order to achieve 90% power.  I do not anticipate that this difference will have an effect on the study's findings, as, with more power, I should be more likely to replicate the original study's findings.
b) The original study was framed as taking approximately 8-10 minutes.  If the authors paid the standard rate on MTurk, this means that workers would have received about 80 cents for taking the original study.  However, I believe that the study can be completed in 3 minutes (and have changed this in the study description and instructions page that workers will see).  Therefore, workers will be paid 30 cents for completing the replication.  It is possible that this could have an effect on the replication's findings if participants are less incentivized to read information closely or answer questions accurately.  However, I have limited resources for running the replication.
c) I do not have the study name or description that the authors posted on MTurk for the original study, so I will be using the study name, "Passage Reading" and the study description, "This session will take approximately 3 minutes and consists of two separate surveys. In each survey, you will be asked to read some information and then to answer several questions about the information that you have read. You will be notified before each survey begins."  Thus, the first page, or the instructions page, of the replication will be slightly different from the original study, as I will repeat this description, along with notifying the user that they should complete the study in a single sitting without distraction (as the original study did).  I do not anticipate that this difference will have an effect on the study's findings, as the instructions provided to participants in the replication will be pretty close to those provided in the original study.
d) Because I have not run any previous experiments on God and risk taking, I will not need to adhere to the authors' preselection rule (see "Planned Sample" section).  However, I added an additional question to the end of my replication ("Have you seen any of the information that you read in these two surveys in a previous survey?").  Only participants who respond "no", rather than "yes", will be included in my analyses.  I do not anticipate that this difference will have an effect on the study's findings, as I am simply ensuring that the workers in my replication were not participants in the original study.
e) Further, I have added one more additional question to the end of my replication ("In your opinion, what were these two surveys about?").  If any participants correctly report the hypothesis of the experiment, they will be excluded from all analyses.  Although the original authors did not do this, I think that this is an important check to include given the minimal separation between the two ostensibly unrelated parts of the survey in the original study (and thus in my replication).  Because I expect few participants to correctly report the hypothesis of the experiment, I do not anticipate that this difference will have an effect on the study's findings.  However, excluding such participants will help ensure that my replication's findings are due to a real effect, rather than demand effects.
f) The authors do not specify whether or not they required that participants answer questions.  I have chosen to require that participants answer questions by adding an error message ("Please answer all of the questions below before continuing to the next page") if at least one question on a page is left unanswered.  All questions will be required, except for the last page in the replication, which will consist of demographics questions and the question in d) above.  For these questions, I will use an error message ("There are unanswered questions on this page. Are you sure you want to continue?") if at least one question on the page is left unanswered, but will not prevent participants from continuing on in the study if they so choose.  I do not anticipate that this difference will have an effect on the study's findings.
g) Although the original authors did not do this, I will run my analyses both on all participants and only on participants who spend at least 5 seconds reading the priming excerpt (see “Analysis Plan”).  These additional analyses will serve as an important check to make sure that MTurk workers are paying attention, which is especially important in a priming study. If many participants do not spend at least 5 seconds reading the priming information, then I would anticipate that these analyses could lead to different results (i.e. the analyses on all participants may not show the hypothesized effect).
