---
title: 'Replication: Data Analysis'
author: "Katherine Flaschen"
date: "February 20, 2016"
output: 
  html_document:
    toc: true
---

```{r Load Packages, message=FALSE, warning=FALSE}
rm(list=ls())
library(tidyr)
library(dplyr)
library(ggplot2)
library(langcog) 
library(rjson)
library(psych)
library(lmerTest)
library(multilevel)
library(MBESS)
library(knitr)
library(broom)
library(effsize)

sem <- function(x) {sd(x, na.rm=TRUE) / sqrt(length(x))}
ci95 <- function(x) {sem(x) * 1.96}
```

# Data prep
```{r Data prep, message=FALSE, warning=FALSE}
path <- "~/Desktop/Classes/Winter2015/Psych254/kflascheProject/Projects/mturk/"
files <- dir(paste0(path,"sandbox-results/"), 
             pattern = "*.json")
d.raw <- data.frame(stringsAsFactors = FALSE)

for (f in files) {
  jf <- paste0(path, "sandbox-results/",f)
  jd <- fromJSON(file=jf)
  id <- data.frame(workerid = jd$WorkerId,
                   timer = as.numeric(jd$answers$data$primetime),
                   interesting = as.numeric(paste0(jd$answers$data$condition_god, jd$answers$data$condition_control)),
                   god_thoughts = jd$answers$data$god_thoughts,
                   god_attncheck = jd$answers$data$god_attncheck,
                   control_thoughts = jd$answers$data$control_thoughts,
                   control_attncheck = jd$answers$data$control_attncheck,
                   m_perceivedrisk1 = as.numeric(jd$answers$data$mlikelihood),
                   m_perceivedrisk2 = as.numeric(jd$answers$data$mserious),
                   m_perceivedrisk3 = as.numeric(jd$answers$data$mcope),
                   m_risk = as.numeric(jd$answers$data$mlikely),
                   wc_perceivedrisk1 = as.numeric(jd$answers$data$wclikelihood),
                   wc_perceivedrisk2 = as.numeric(jd$answers$data$wcserious),
                   wc_perceivedrisk3 = as.numeric(jd$answers$data$wccope),
                   wc_risk = as.numeric(jd$answers$data$wclikely),
                   s_perceivedrisk1 = as.numeric(jd$answers$data$slikelihood),
                   s_perceivedrisk2 = as.numeric(jd$answers$data$sserious),
                   s_perceivedrisk3 = as.numeric(jd$answers$data$s_cope),
                   s_risk = as.numeric(jd$answers$data$slikely),
                   belief_god = jd$answers$data$godbelief,
                   gender = jd$answers$data$gen,
                   age = as.numeric(jd$answers$data$age),
                   race = jd$answers$data$race_ethn,
                   english = jd$answers$data$engl,
                   check_seen = jd$answers$data$previouscheck,
                   check_hypothesis = jd$answers$data$studycheck,
                   stringsAsFactors=FALSE)
  d.raw <- bind_rows(d.raw, id)
}

# Number of participants
length(unique(d.raw$workerid))
```

#Data cleanup
```{r Data cleanup, message=FALSE, warning=FALSE}
#Clean up factor structure
d.raw$belief_god <- factor(d.raw$belief_god)
levels(d.raw$belief_god) <- c("No","Yes")

d.raw$gender <- factor(d.raw$gender)
levels(d.raw$gender) <- c("Female","Male","Other")

d.raw$english <- factor(d.raw$english)
levels(d.raw$english) <- c("No","Yes")

d.raw$check_seen <- factor(d.raw$check_seen)
levels(d.raw$check_seen) <- c("No","Yes")

#Create Condition Variable
d.raw$condition <- factor(ifelse(d.raw$god_thoughts=="", "Control", "God"))
```

#Exclusion Criteria
```{r Exclusions, message=FALSE, warning=FALSE}
#Remove participants who have seen the study before
d = d.raw[d.raw$check_seen=="No",]

#Remove participants who correctly report study hypothesis under "check_hypothesis"
#d= d[-c(2),]
length(unique(d.raw$workerid)) - length(unique(d$workerid)) #Number of participants excluded

#Create additional dataframe with only participants who spend at least 5 seconds reading prime
d.time = d[d$timer>=5,] 
length(unique(d$workerid)) - length(unique(d.time$workerid)) #Number of participants excluded
```

#Demographics
```{r Demographics, message=FALSE, warning=FALSE}
#Full dataframe
#Age
summary(d$age)
sd(d$age, na.rm=TRUE)

#Gender
table(d$gender)
Male = sum(d$gender=="Male")/length(d$gender)
Male
Female = sum(d$gender=="Female")/length(d$gender)
Female
Other = sum(d$gender=="Other")/length(d$gender)
Other

#Dataframe with exclusions
#Age
summary(d.time$age)
sd(d.time$age, na.rm=TRUE)

#Gender
table(d.time$gender)
Male = sum(d.time$gender=="Male")/length(d.time$gender)
Male
Female = sum(d.time$gender=="Female")/length(d.time$gender)
Female
Other = sum(d.time$gender=="Other")/length(d.time$gender)
Other
```

#Preliminary Analysis: Linear Mixed Model
```{r Analysis1, message=FALSE, warning=FALSE}
#Full dataframe
#Turn data into long form
d.gathered <- d %>%
  gather(scenario, rating, 
         starts_with("m_"), starts_with("wc_"), starts_with("s_")) %>%
  separate(scenario, c("scenario", "risk"), "_") %>%
  spread(risk, rating)

#Visualize: Histograms
#Risk-taking
qplot(risk, data = d.gathered, binwidth=.5) + theme_bw() + xlim(0,7)
#Is there an effect of condition on risk-taking?
qplot(risk, data = d.gathered, facets=~condition, binwidth=.5) + theme_bw() + xlim(0,7)
#Does scenario moderate the effect of condition on risk-taking?
qplot(risk, data = d.gathered, facets=condition~scenario, binwidth=.5) + theme_bw() + xlim(0,7)

#Analysis
model1 = lmer(risk ~ condition + scenario + (1 | workerid), REML = TRUE, d.gathered)
model2 = lmer(risk ~ condition*scenario + (1 | workerid), REML = TRUE, d.gathered)
anova(model1, model2, refit = FALSE)

#Graph
ms1 <- d.gathered %>% 
  group_by(condition, scenario) %>% 
  summarise("mean.risk" = mean(risk),
            "sem" = sem(risk),
            "ci.lower" = mean(risk) - ci95(risk),
            "ci.upper" = mean(risk) + ci95(risk))

ggplot(ms1, aes(x = condition, y=mean.risk, fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin = mean.risk-sem, 
                     ymax = mean.risk+sem)) +
  facet_wrap(~scenario) +
  theme_bw() +
  ylim(0,7)

#Dataframe with exclusions
#Turn data into long form
d.gathered.time <- d.time %>%
  gather(scenario, rating, 
         starts_with("m_"), starts_with("wc_"), starts_with("s_")) %>%
  separate(scenario, c("scenario", "risk"), "_") %>%
  spread(risk, rating)

#Visualize: Histograms
#Risk-taking
qplot(risk, data = d.gathered.time, binwidth=.5) + theme_bw()
#Is there an effect of condition on risk-taking?
qplot(risk, data = d.gathered.time, facets=~condition, binwidth=.5) + theme_bw()
#Does scenario moderate the effect of condition on risk-taking?
qplot(risk, data = d.gathered.time, facets=condition~scenario, binwidth=.5) + theme_bw()

#Analysis
model3 = lmer(risk ~ condition + scenario + (1 | workerid), REML = TRUE, d.gathered.time)
model4 = lmer(risk ~ condition*scenario + (1 | workerid), REML = TRUE, d.gathered.time)
anova(model3, model4, refit = FALSE)

#Graph
ms2 <- d.gathered.time %>% 
  group_by(condition, scenario) %>% 
  summarise("mean.risk" = mean(risk),
            "sem" = sem(risk),
            "ci.lower" = mean(risk) - ci95(risk),
            "ci.upper" = mean(risk) + ci95(risk))

#ggplot(ms2, aes(x = condition, y=mean.risk, fill=condition)) +
#  geom_bar(stat="identity", position="dodge") +
#  geom_errorbar(aes(ymin = mean.risk-sem, 
#                     ymax = mean.risk+sem)) +
#  facet_wrap(~scenario) +
#  theme_bw() +
#  ylim(0,7)
```

#Main Analysis: Mediation
**Data Setup**
```{r Analysis2_Setup, message=FALSE, warning=FALSE}
#Full Dataframe
#Reverse code "cope" variable
d <- d %>%
  mutate(m_perceivedrisk3.reverse = as.numeric(reverse.code(-1, m_perceivedrisk3))) %>%
  mutate(wc_perceivedrisk3.reverse = as.numeric(reverse.code(-1, wc_perceivedrisk3))) %>%
  mutate(s_perceivedrisk3.reverse = as.numeric(reverse.code(-1, s_perceivedrisk3)))

#Alpha for Perceived Risk Index: Nine Items
alpha_pr= cbind(d$m_perceivedrisk1, d$m_perceivedrisk2, d$m_perceivedrisk3.reverse, d$wc_perceivedrisk1, d$wc_perceivedrisk2, d$wc_perceivedrisk3.reverse, d$s_perceivedrisk1, d$s_perceivedrisk2, d$s_perceivedrisk3.reverse)
ICC(alpha_pr, missing=F)[[1]]$ICC[6]

#Alpha for Risk Index: Three Items
alpha_r= cbind(d$m_risk, d$wc_risk, d$s_risk)
ICC(alpha_r, missing=F)[[1]]$ICC[6]

#Create new variables
d <- d %>%
  mutate(m_perceivedrisk = (m_perceivedrisk1 + m_perceivedrisk2 + m_perceivedrisk3.reverse)/3) %>%
  mutate(wc_perceivedrisk = (wc_perceivedrisk1 + wc_perceivedrisk2 + wc_perceivedrisk3.reverse)/3) %>%
  mutate(s_perceivedrisk = (s_perceivedrisk1 + s_perceivedrisk2 + s_perceivedrisk3.reverse)/3) %>%
  mutate(likelihood_pr = (m_perceivedrisk1 + wc_perceivedrisk1 + s_perceivedrisk1)/3) %>%
  mutate(seriousness_pr = (m_perceivedrisk2 + wc_perceivedrisk2 + s_perceivedrisk2)/3) %>%
  mutate(cope_pr = (m_perceivedrisk3.reverse + wc_perceivedrisk3.reverse + s_perceivedrisk3.reverse)/3) %>%
  mutate(perceivedriskindex = (m_perceivedrisk + wc_perceivedrisk + s_perceivedrisk)/3) %>%
  mutate(riskindex = (m_risk + wc_risk + s_risk)/3)

#Dataframe with Exclusions
#Reverse code "cope" variable
d.time <- d.time %>%
  mutate(m_perceivedrisk3.reverse = as.numeric(reverse.code(-1, m_perceivedrisk3))) %>%
  mutate(wc_perceivedrisk3.reverse = as.numeric(reverse.code(-1, wc_perceivedrisk3))) %>%
  mutate(s_perceivedrisk3.reverse = as.numeric(reverse.code(-1, s_perceivedrisk3)))

#Alpha for Perceived Risk Index: Nine Items
alpha_pr2= cbind(d.time$m_perceivedrisk1, d.time$m_perceivedrisk2, d.time$m_perceivedrisk3.reverse, d.time$wc_perceivedrisk1, d.time$wc_perceivedrisk2, d.time$wc_perceivedrisk3.reverse, d.time$s_perceivedrisk1, d.time$s_perceivedrisk2, d.time$s_perceivedrisk3.reverse)
ICC(alpha_pr2, missing=F)[[1]]$ICC[6]

#Alpha for Risk Index: Three Items
alpha_r2= cbind(d.time$m_risk, d.time$wc_risk, d.time$s_risk)
ICC(alpha_r2, missing=F)[[1]]$ICC[6]

#Create new variables
d.time <- d.time %>%
  mutate(m_perceivedrisk = (m_perceivedrisk1 + m_perceivedrisk2 + m_perceivedrisk3.reverse)/3) %>%
  mutate(wc_perceivedrisk = (wc_perceivedrisk1 + wc_perceivedrisk2 + wc_perceivedrisk3.reverse)/3) %>%
  mutate(s_perceivedrisk = (s_perceivedrisk1 + s_perceivedrisk2 + s_perceivedrisk3.reverse)/3) %>%
  mutate(likelihood_pr = (m_perceivedrisk1 + wc_perceivedrisk1 + s_perceivedrisk1)/3) %>%
  mutate(seriousness_pr = (m_perceivedrisk2 + wc_perceivedrisk2 + s_perceivedrisk2)/3) %>%
  mutate(cope_pr = (m_perceivedrisk3.reverse + wc_perceivedrisk3.reverse + s_perceivedrisk3.reverse)/3) %>%
  mutate(perceivedriskindex = (m_perceivedrisk + wc_perceivedrisk + s_perceivedrisk)/3) %>%
  mutate(riskindex = (m_risk + wc_risk + s_risk)/3)
```

**Visualize**
```{r Analysis2_Visualize, message=FALSE, warning=FALSE}
#Full dataframe
#Histograms
#Risk
qplot(riskindex, data = d, binwidth=.5) + theme_bw() + xlim(0,7)
#Risk by Condition
qplot(riskindex, data = d, facets=~condition, binwidth=.5) + theme_bw() + xlim(0,7)
#Pereived Risk
qplot(perceivedriskindex, data = d, binwidth=.5) + theme_bw() + xlim(0,7)
#Perceived Risk by Condition
qplot(perceivedriskindex, data = d, facets=~condition, binwidth=.5) + theme_bw() + xlim(0,7)

#Graphs
ms3 <- d %>% 
  group_by(condition) %>% 
  summarise("mean.risk" = mean(riskindex),
            "sem.risk" = sem(riskindex),
            "ci.lower.risk" = mean(riskindex) - ci95(riskindex),
            "ci.upper.risk" = mean(riskindex) + ci95(riskindex),
            "mean.perceivedrisk" = mean(perceivedriskindex),
            "sem.perceivedrisk" = sem(perceivedriskindex),
            "ci.lower.perceivedrisk" = mean(perceivedriskindex) - ci95(perceivedriskindex),
            "ci.upper.perceivedrisk" = mean(perceivedriskindex) + ci95(perceivedriskindex))

#Risk
ggplot(ms3, aes(x = condition, y=mean.risk, fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin = mean.risk-sem.risk, 
                     ymax = mean.risk+sem.risk)) +
  theme_bw() +
  ylim(0,7)

#Perceived Risk
ggplot(ms3, aes(x = condition, y=mean.perceivedrisk, fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin = mean.perceivedrisk-sem.perceivedrisk, 
                     ymax = mean.perceivedrisk+sem.perceivedrisk)) +
  theme_bw() +
  ylim(0,7)

#Dataframe with exclusions
#Histograms
#Risk
qplot(riskindex, data = d.time, binwidth=.5) + theme_bw() + xlim(0,7)
#Risk by Condition
qplot(riskindex, data = d.time, facets=~condition, binwidth=.5) + theme_bw() + xlim(0,7)
#Pereived Risk
qplot(perceivedriskindex, data = d.time, binwidth=.5) + theme_bw() + xlim(0,7)
#Perceived Risk by Condition
qplot(perceivedriskindex, data = d.time, facets=~condition, binwidth=.5) + theme_bw() + xlim(0,7)

#Graphs
ms4 <- d.time %>% 
  group_by(condition) %>% 
  summarise("mean.risk" = mean(riskindex),
            "sem.risk" = sem(riskindex),
            "ci.lower.risk" = mean(riskindex) - ci95(riskindex),
            "ci.upper.risk" = mean(riskindex) + ci95(riskindex),
            "mean.perceivedrisk" = mean(perceivedriskindex),
            "sem.perceivedrisk" = sem(perceivedriskindex),
            "ci.lower.perceivedrisk" = mean(perceivedriskindex) - ci95(perceivedriskindex),
            "ci.upper.perceivedrisk" = mean(perceivedriskindex) + ci95(perceivedriskindex))

#Risk
ggplot(ms4, aes(x = condition, y=mean.risk, fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin = mean.risk-sem.risk, 
                     ymax = mean.risk+sem.risk)) +
  theme_bw() +
  ylim(0,7)

#Perceived Risk
ggplot(ms4, aes(x = condition, y=mean.perceivedrisk, fill=condition)) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin = mean.perceivedrisk-sem.perceivedrisk, 
                     ymax = mean.perceivedrisk+sem.perceivedrisk)) +
  theme_bw() +
  ylim(0,7)
```

**Main Analysis: (Overall) Mediation**
```{r Analysis2_OverallMediation, message=FALSE, warning=FALSE}
#Function for printing cleaner output from sobel
sob_print <- function(sob){
 df <- do.call(rbind, sob)
 rnames <- rownames(df)
 rnames[c(1,3,6)] <- c("Mod1: Y~X", "Mod2: Y~X+M", "Mod3: M~X")
 rownames(df) <- rnames
 
 return(list("Models"=df[1:7,],
             "Vals"=data.frame("IndirectEffect"=df[8,1],
                               "SE"=df[9,1],
                               "Z"=df[10,1],
                               "N"=df[11,1])))
}

#Full Dataframe
#Sobel
sobel = sobel(d$condition, d$perceivedriskindex, d$riskindex)
sobel_chart <- sob_print(sobel)
kable(sobel_chart$Models)
kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d$condition), mediator = d$perceivedriskindex, dv = d$riskindex, conf.level=.95, bootstrap=TRUE, B=5000)

#Dataframe with Exclusions
#Sobel
#Check to make sure this works when sample size is larger:
#sobel = sobel(d.time$condition, d.time$perceivedriskindex, d.time$riskindex) 
#sobel_chart <- sob_print(sobel)
#kable(sobel_chart$Models)
#kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d.time$condition), mediator = d.time$perceivedriskindex, dv = d.time$riskindex, conf.level=.95, bootstrap=TRUE, B=5000)
```

**Additional Analysis: Mediation for each scenario**
```{r Analysis2_Mediation_EachScenario, message=FALSE, warning=FALSE}
#Full Dataframe
#Scenario 1: Motorcycle
#Sobel
sobel = sobel(d$condition, d$m_perceivedrisk, d$m_risk)
sobel_chart <- sob_print(sobel)
kable(sobel_chart$Models)
kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d$condition), mediator = d$m_perceivedrisk, dv = d$m_risk, conf.level=.95, bootstrap=TRUE, B=5000)

#Scenario 2: Wilderness Camping
#Sobel
sobel = sobel(d$condition, d$wc_perceivedrisk, d$wc_risk)
sobel_chart <- sob_print(sobel)
kable(sobel_chart$Models)
kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d$condition), mediator = d$wc_perceivedrisk, dv = d$wc_risk, conf.level=.95, bootstrap=TRUE, B=5000)

#Scenario 3: Skiing
#Sobel
sobel = sobel(d$condition, d$s_perceivedrisk, d$s_risk)
sobel_chart <- sob_print(sobel)
kable(sobel_chart$Models)
kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d$condition), mediator = d$s_perceivedrisk, dv = d$s_risk, conf.level=.95, bootstrap=TRUE, B=5000)


#Dataframe with Exclusions
#Scenario 1: Motorcycle
#Sobel
#Check to make sure this works when sample size is larger:
#sobel = sobel(d.time$condition, d.time$m_perceivedrisk, d.time$m_risk) 
#sobel_chart <- sob_print(sobel)
#kable(sobel_chart$Models)
#kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d.time$condition), mediator = d.time$m_perceivedrisk, dv = d.time$m_risk, conf.level=.95, bootstrap=TRUE, B=5000)

#Scenario 2: Wilderness Camping
#Sobel
#Check to make sure this works when sample size is larger:
#sobel = sobel(d.time$condition, d.time$wc_perceivedrisk, d.time$wc_risk) 
#sobel_chart <- sob_print(sobel)
#kable(sobel_chart$Models)
#kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d.time$condition), mediator = d.time$wc_perceivedrisk, dv = d.time$wc_risk, conf.level=.95, bootstrap=TRUE, B=5000)

#Scenario 3: Skiing
#Sobel
#Check to make sure this works when sample size is larger:
#sobel = sobel(d.time$condition, d.time$s_perceivedrisk, d.time$s_risk) 
#sobel_chart <- sob_print(sobel)
#kable(sobel_chart$Models)
#kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d.time$condition), mediator = d.time$s_perceivedrisk, dv = d.time$s_risk, conf.level=.95, bootstrap=TRUE, B=5000)
```

**Additional Analysis: Mediation by each perceived risk item**
```{r Analysis2_Mediation_EachPRItem, message=FALSE, warning=FALSE}
#Full Dataframe
#Likelihood
#Sobel
sobel = sobel(d$condition, d$likelihood_pr, d$riskindex)
sobel_chart <- sob_print(sobel)
kable(sobel_chart$Models)
kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d$condition), mediator = d$likelihood_pr, dv = d$riskindex, conf.level=.95, bootstrap=TRUE, B=5000)

#Seriousness
#Sobel
sobel = sobel(d$condition, d$seriousness_pr, d$riskindex)
sobel_chart <- sob_print(sobel)
kable(sobel_chart$Models)
kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d$condition), mediator = d$seriousness_pr, dv = d$riskindex, conf.level=.95, bootstrap=TRUE, B=5000)

#Coping
#Sobel
sobel = sobel(d$condition, d$cope_pr, d$riskindex)
sobel_chart <- sob_print(sobel)
kable(sobel_chart$Models)
kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d$condition), mediator = d$cope_pr, dv = d$riskindex, conf.level=.95, bootstrap=TRUE, B=5000)


#Dataframe with Exclusions
#Likelihood
#Sobel
#Check to make sure this works when sample size is larger:
#sobel = sobel(d.time$condition, d.time$likelihood_pr, d.time$riskindex) 
#sobel_chart <- sob_print(sobel)
#kable(sobel_chart$Models)
#kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d.time$condition), mediator = d.time$likelihood_pr, dv = d.time$riskindex, conf.level=.95, bootstrap=TRUE, B=5000)

#Seriousness
#Sobel
#Check to make sure this works when sample size is larger:
#sobel = sobel(d.time$condition, d.time$seriousness_pr, d.time$riskindex) 
#sobel_chart <- sob_print(sobel)
#kable(sobel_chart$Models)
#kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d.time$condition), mediator = d.time$seriousness_pr, dv = d.time$riskindex, conf.level=.95, bootstrap=TRUE, B=5000)

#Coping
#Sobel
#Check to make sure this works when sample size is larger:
#sobel = sobel(d.time$condition, d.time$cope_pr, d.time$riskindex) 
#sobel_chart <- sob_print(sobel)
#kable(sobel_chart$Models)
#kable(sobel_chart$Vals)

#Bootstrapping
#Sample size currently too small:
#mediation(x = as.numeric(d.time$condition), mediator = d.time$cope_pr, dv = d.time$riskindex, conf.level=.95, bootstrap=TRUE, B=5000)
```

#Additional Analysis: Moderation by God Belief?
```{r Analysis3_Moderation, message=FALSE, warning=FALSE}
#Full dataframe
#Summary
table(d$condition, d$belief_god)
ms_beliefgod <- d %>% 
  group_by(belief_god, condition) %>% 
  summarise("mean" = mean(riskindex),
            "sd" = sd(riskindex))

#Best model?
model5 = lm(riskindex ~ condition, d)
model6 = lm(riskindex ~ condition + belief_god, d)
model7 = lm(riskindex ~ condition*belief_god, d)
anova(model5, model6, model7)           

#Effect of Condition for Non-believers
summary(lm(riskindex ~ condition, d[d$belief_god=="No",]))
d.extra = d[d$belief_god=="No",]
cohen.d(c(0,1), as.numeric(d.extra$condition))

#Effect of Condition for Believers
#summary(lm(riskindex ~ condition, d[d$belief_god=="Yes",]))
d.extra2 = d[d$belief_god=="Yes",]
cohen.d(c(0,1), as.numeric(d.extra2$condition))

#Dataframe with exclusions
#Summary
table(d.time$condition, d.time$belief_god)
ms_beliefgod2 <- d.time %>% 
  group_by(belief_god, condition) %>% 
  summarise("mean" = mean(riskindex),
            "sd" = sd(riskindex))

#Best model?
model8 = lm(riskindex ~ condition, d.time)
model9 = lm(riskindex ~ condition + belief_god, d.time)
model10 = lm(riskindex ~ condition*belief_god, d.time)
anova(model8, model9, model10)           

#Effect of Condition for Non-believers
#summary(lm(riskindex ~ condition, d.time[d.time$belief_god=="No",]))
d.extra3 = d.time[d.time$belief_god=="No",]
cohen.d(c(0,1), as.numeric(d.extra3$condition))

#Effect of Condition for Believers
#summary(lm(riskindex ~ condition, d.time[d.time$belief_god=="Yes",]))
d.extra4 = d.time[d.time$belief_god=="Yes",]
cohen.d(c(0,1), as.numeric(d.extra4$condition))
```
